name: Daily Tests Run

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install latest Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libasound2

      - name: Run Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=daily-suite.xml
