name: Daily Tests Run

on:
  push:
    branches:
      - master

  schedule:
    - cron: "30 15 2 12 *"   # 9 PM IST → 15:30 UTC on 2 Dec every year

  workflow_dispatch:

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install latest Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=daily-suite.xml
