name: Daily Tests Run

on:
  push:
    branches:
      - master
  schedule:
    # - cron: "0 8 * * *" #1:30 PM runs daily
    # Format: minute hour day-of-month month day-of-week
    #   - minute: 0-59
    #   - hour: 0-23
    #   - day-of-month: 1-31
    #   - month: 1-12 (or JAN-DEC)
    #   - day-of-week: 0-6 (Sunday-Saturday, or SUN-SAT)
    - cron : '50 20 26 11 *' # 08:50 PM UTC on the 26th of November, regardless of the day of the week.
  workflow_dispatch:

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install latest Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=daily-suite.xml
